#!/bin/sh


pipewire &
pipewire-pulse &
wireplumber &
picom --backend xrender -b &
nm-applet &
volumeicon &
pcmanfm --daemon-mode &
flameshot &
kdeconnectd &
kdeconnect-indicator &
lxqt-policykit-agent &
